import random
import datetime 
causes_of_death = [
    "Heart disease",
    "Cancer",
    "Stroke",
    "Respiratory diseases",
    "Accidents",
    "Alzheimer's disease",
    "Diabetes",
    "Influenza and pneumonia",
    "Kidney disease",
    "Suicide",
    "Liver disease",
    "Hypertension",
    "Parkinson's disease",
    "Septicemia",
    "Chronic lower respiratory diseases",
    "HIV/AIDS",
    "Tuberculosis",
    "Malaria",
    "Breast cancer",
    "Prostate cancer",
    "Colon cancer",
    "Road traffic accidents",
    "Drowning",
    "Drug overdose",
    "Homicide",
    "Malnutrition",
    "Complications during childbirth",
    "Pulmonary embolism",
    "Cerebrovascular diseases",
    "Chronic obstructive pulmonary disease (COPD)",
    "Liver cirrhosis",
    "Heat-related illness",
    "Electrocution",
    "Natural disasters",
    "Terrorist attacks",
    "War",
    "Drug-resistant infections",
    "Euthanasia",
    "Poisoning",
    "Fire-related injuries",
    "Radiation exposure",
    "Work-related injuries",
    "Obesity-related complications",
    "Extreme temperatures",
    "Medical errors",
    "Asthma",
    "Epilepsy",
    "Leukemia",
    "Pancreatic cancer",
    "Ovarian cancer",
    "Lung cancer",
    "Brain tumor",
    "Huntington's disease",
    "Multiple sclerosis",
    "Sepsis",
    "Tetanus",
    "Rabies",
    "Yellow fever",
    "Zika virus",
    "Ebola virus",
    "COVID-19",
    "Avian influenza",
    "Swine flu",
    "Cholera",
    "Typhoid fever",
    "Diphtheria",
    "Measles",
    "Whooping cough",
    "Rubella",
    "Mumps",
    "Tetanus",
    "Polio",
    "Meningitis",
    "Encephalitis",
    "Syphilis",
    "Gonorrhea",
    "Chlamydia",
    "Hepatitis",
    "HIV/AIDS",
    "Herpes",
    "Genital warts",
    "Gonorrhea",
    "Chlamydia",
    "Syphilis",
    "Trichomoniasis",
    "Pelvic inflammatory disease",
    "Thyroid disorders",
    "Eating disorders",
    "Sleep disorders",
    "Fibromyalgia",
    "Chronic fatigue syndrome",
    "Autoimmune diseases",
    "Allergies",
    "Anaphylaxis",
    "Arthritis",
    "Osteoporosis",
    "Gout",
    "Lupus",
    "Scleroderma",
    "Crohn's disease",
    "Ulcerative colitis",
    "Celiac disease",
    "Diverticulitis",
    "Hemorrhoids",
    "Gallstones",
    "Kidney stones",
    "Bladder stones",
    "Pancreatitis",
    "Gastroesophageal reflux disease (GERD)",
    "Peptic ulcer disease",
    "Irritable bowel syndrome (IBS)",
    "Constipation",
    "Diarrhea",
    "Gastritis",
    "Gastroenteritis",
    "Appendicitis",
    "Hernia",
    "Cirrhosis",
    "Hepatitis",
    "Gastric cancer",
    "Esophageal cancer",
    "Colorectal cancer",
    "Liver cancer",
    "Pancreatic cancer",
    "Gallbladder cancer",
    "Small intestine cancer",
    "Anal cancer",
    "Stomach cancer",
    "Throat cancer",
    "Oral cancer",
    "Laryngeal cancer",
    "Nasopharyngeal cancer",
    "Thyroid cancer",
    "Tracheal cancer",
    "Bronchial cancer",
    "Lung cancer",
    "Breast cancer",
    "Ovarian cancer",
    "Uterine cancer",
    "Cervical cancer",
    "Vaginal cancer",
    "Vulvar cancer",
    "Prostate cancer",
    "Testicular cancer",
    "Penile cancer",
    "Bladder cancer",
    "Kidney cancer",
    "Renal pelvis cancer",
    "Ureteral cancer",
    "Urethral cancer",
    "Adrenal cancer",
    "Eye cancer",
    "Brain cancer",
    "Spinal cord cancer",
    "Bone cancer",
    "Soft tissue sarcoma",
    "Melanoma",
    "Non-melanoma skin cancer",
    "Kaposi's sarcoma",
    "Mesothelioma",
    "Gestational trophoblastic disease",
    "Wilms' tumor",
    "Neuroblastoma",
    "Rhabdomyosarcoma",
    "Retinoblastoma",
    "Hepatoblastoma",
    "Medulloblastoma",
    "Ewing's sarcoma",
    "Osteosarcoma",
    "Chondrosarcoma",
    "Fibrosarcoma",
    "Leiomyosarcoma",
    "Angiosarcoma",
    "Synovial sarcoma",
    "Malignant peripheral nerve sheath tumor",
    "Glioma",
    "Astrocytoma",
    "Oligodendroglioma",
    "Ependymoma",
    "Craniopharyngioma",
    "Pituitary adenoma",
    "Meningioma",
    "Neurofibroma",
    "Schwannoma",
    "Lipoma",
    "Hemangioma",
    "Lymphoma",
    "Hodgkin lymphoma",
    "Non-Hodgkin lymphoma",
    "Multiple myeloma",
    "Chronic lymphocytic leukemia",
    "Acute lymphoblastic leukemia",
    "Acute myeloid leukemia",
    "Chronic myeloid leukemia",
    "Myelodysplastic syndromes",
    "Myeloproliferative neoplasms",
    "Waldenström macroglobulinemia",
    "Amyloidosis",
    "Essential thrombocythemia",
    "Polycythemia vera",
    "Primary myelofibrosis",
    "Hemophagocytic lymphohistiocytosis",
    "Castleman disease",
    "Langerhans cell histiocytosis",
    "Erdheim-Chester disease",
    "Rosai-Dorfman disease",
    "Juvenile xanthogranuloma",
    "Familial hemophagocytic lymphohistiocytosis",
    "Histiocytic sarcoma",
    "Histiocytosis",
    "Eosinophilic granuloma",
    "Hand-Schüller-Christian disease",
    "Letterer-Siwe disease",
    "Ac" ]
str=input("ENTER YOUR NAME:")
st2=input("Enter the your Month of Birth:")
print(random.choice(causes_of_death))
# print()